export const levels = {
  basic: [
    { note: "C1.png" },
    { note: "D1.png" },
    { note: "E1.png" },
    { note: "F1.png" },
    { note: "G1.png" },
    { note: "A1.png" },
    { note: "B1.png" },
    { note: "C2.png" }
  ],

  beginner: [
    { note: "A0.png" },
    { note: "B0.png" },
    { note: "C1.png" },
    { note: "D1.png" },
    { note: "E1.png" },
    { note: "F1.png" },
    { note: "G1.png" },
    { note: "A1.png" },
    { note: "B1.png" },
    { note: "C2.png" },
    { note: "Fsharp1.png" },
    { note: "Csharp1.png" },
    { note: "Gsharp1.png" },
    { note: "Bflat1.png" },
    { note: "Eflat1.png" },
    { note: "Aflat1.png" },
    { note: "Csharp2.png" },
    { note: "Dflat2.png" },
    { note: "D2.png" }
  ],

  intermediate: [
    { note: "Fsharp0.png" },
    { note: "G0.png" },
    { note: "Gsharp0.png" },
    { note: "Aflat0.png" },
    { note: "A0.png" },
    { note: "Asharp0.png" },
    { note: "Bflat0.png" },
    { note: "B0.png" },
    { note: "C1.png" },
    { note: "Csharp1.png" },
    { note: "Dflat1.png" },
    { note: "D1.png" },
    { note: "Dsharp1.png" },
    { note: "Eflat1.png" },
    { note: "E1.png" },
    { note: "F1.png" },
    { note: "Fsharp1.png" },
    { note: "G1.png" },
    { note: "Gsharp1.png" },
    { note: "Aflat1.png" },
    { note: "A1.png" },
    { note: "Asharp1.png" },
    { note: "Bflat1.png" },
    { note: "B1.png" },
    { note: "C2.png" },
    { note: "Csharp2.png" },
    { note: "Dflat2.png" },
    { note: "D2.png" },
    { note: "Dsharp2.png" },
    { note: "Eflat2.png" },
    { note: "E2.png" },
    { note: "F2.png" },
    { note: "Fsharp2.png" }
  ],

  advanced: [
    { note: "Fsharp0.png" },
    { note: "G0.png" },
    { note: "Gsharp0.png" },
    { note: "Aflat0.png" },
    { note: "A0.png" },
    { note: "Asharp0.png" },
    { note: "Bflat0.png" },
    { note: "B0.png" },
    { note: "C1.png" },
    { note: "Csharp1.png" },
    { note: "Dflat1.png" },
    { note: "D1.png" },
    { note: "Dsharp1.png" },
    { note: "Eflat1.png" },
    { note: "E1.png" },
    { note: "Esharp1.png" },
    { note: "Fflat1.png" },
    { note: "F1.png" },
    { note: "Fsharp1.png" },
    { note: "G1.png" },
    { note: "Gsharp1.png" },
    { note: "Aflat1.png" },
    { note: "A1.png" },
    { note: "Asharp1.png" },
    { note: "Bflat1.png" },
    { note: "B1.png" },
    { note: "C2.png" },
    { note: "Csharp2.png" },
    { note: "Dflat2.png" },
    { note: "D2.png" },
    { note: "Dsharp2.png" },
    { note: "Eflat2.png" },
    { note: "E2.png" },
    { note: "F2.png" },
    { note: "Fsharp2.png" },
    { note: "G2.png" },
    { note: "Gsharp2.png" },
    { note: "Aflat2.png" },
    { note: "A2.png" },
    { note: "Asharp2.png" },
    { note: "Bflat2.png" },
    { note: "B2.png" },
    { note: "C3.png" }
  ]
};
